keys/urls.py
from django.urls import path

from keys.views import KeyListView, KeyCreateView, KeyDeleteView

urlpatterns = [
    path("list/", KeyListView.as_view(), name="list_keys"),
    path("create/", KeyCreateView.as_view(), name="create_key"),
    path("<int:pk>/delete/", KeyDeleteView.as_view(), name="delete_key")
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("tasks/", include("tasks.urls")),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("keys/", include("keys.urls")),
    path("admin/", admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

keys/models.py
from django.db import models
from django.forms import CharField


class Key(models.Model):
    A = "A"
    BFLAT = "B-flat/A#"
    B = "B"
    C = "C"
    CSHARP = "C#/D-flat"
    D = "D"
    EFLAT = "E-flat/D#"
    E = "E"
    F = "F"
    FSHARP = "F#"
    G = "G"
    GSHARP = "A-flat/G#"
    KEY_NAME_CHOICES = [
        (A, "A"),
        (BFLAT, "B-flat/A#"),
        (B, "B"),
        (C, "C"),
        (CSHARP, "C#/D-flat"),
        (D, "D"),
        (EFLAT, "E-flat/D#"),
        (E, "E"),
        (F, "F"),
        (FSHARP, "F#"),
        (G, "G"),
        (GSHARP, "A-flat/G#"),
    ]

    name = models.CharField(max_length=20, choices=KEY_NAME_CHOICES, default=A)
    date = models.DateField()
    tempo = models.CharField(max_length=200, default="None specified")
    notes = models.TextField()
    assignee = models.ForeignKey(
        "auth.User", related_name="keys", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

keys/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin


from keys.models import Key


# Create your views here.


class KeyListView(LoginRequiredMixin, ListView):
    model = Key
    template_name = "keys/list.html"
    # extra_context = {"key": "A"}  # method call to def random

    def get_queryset(self):
        return Key.objects.filter(assignee=self.request.user)

    # #def random_key(request):
    #     my_list = [
    #         "A",
    #         "A#",
    #         "B-flat",
    #         "B",
    #         "C",
    #         "C#",
    #         "D-flat",
    #         "D",
    #         "D#",
    #         "E-flat",
    #         "E",
    #         "F",
    #         "F#",
    #         "G",
    #     ]
    #     rand_key = random.choice(my_list)
    #     html = "<b>Not sure? Random Key:</b> %s" % rand_key
    #     return render(request, html)  # add context


class KeyCreateView(LoginRequiredMixin, CreateView):
    model = Key
    template_name = "keys/create.html"
    fields = [
        "name",
        "date",
        "tempo",
        "notes",
    ]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.assignee = self.request.user
        item.save()
        return redirect("list_keys")


class KeyDeleteView(LoginRequiredMixin, DeleteView):
    model = Key
    template_name = "keys/delete.html"
    success_url = reverse_lazy("list_keys")

keys/templates/keys/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Add scale key</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Add Key</button>
            </form>
        </div>
    </main>

{% endblock content %}

keys/templates/keys/list.html
{% extends 'base.html' %}

{% block content %}

    <main>
        <div class = "project-list">
            <h1>Keys Practiced</h1>
            <p><a href="{%url "create_key" %}">Add a new key you've practiced</a></p>
            {% if key_list|length == 0 %}
                <p>You haven't listed any scale keys</p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Key Name</th>
                            <th>Date</th>
                            <th>Tempo</th>
                            <th>Notes</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for key in key_list %}
                            <tr>
                                <td> {{ key.name }} </td>
                                <td>{{ key.date }}</td>
                                <td>{{ key.tempo }}</td>
                                <td>{{ key.notes }}</td>
                                <td>
                                    <form method="post" action="{% url 'delete_key' key.id %}">
                                      {% csrf_token %}
                                      <input type="hidden" name="delete" value="True" />
                                      <button>X</button>
                                    </form>
                                  </td>
                                </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>

    </main>

{% endblock content %}