keys/urls.py
from django.urls import path

from keys.views import KeyListView, KeyCreateView, KeyDeleteView

urlpatterns = [
    path("list/", KeyListView.as_view(), name="list_keys"),
    path("create/", KeyCreateView.as_view(), name="create_key"),
    path("<int:pk>/delete/", KeyDeleteView.as_view(), name="delete_key")
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
    TaskDeleteView,
)

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="delete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("tasks/", include("tasks.urls")),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("keys/", include("keys.urls")),
    path("admin/", admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

tasks/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    is_completed = models.BooleanField(default=False)
    goal_time = models.CharField(max_length=100, default="None Specified")
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        "auth.User",
        related_name="tasks",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name

tasks/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from tasks.models import Task


# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "goal_time", "project"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.assignee = self.request.user
        item.save()
        return redirect("show_project", pk=item.project.id)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/mine.html"
    fields = [
        "is_completed",
    ]
    success_url = reverse_lazy("show_my_tasks")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/mine.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/delete.html"
    success_url = reverse_lazy("show_my_tasks")

tasks/templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}

    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>

{% endblock content %}

tasks/templates/tasks/delete.html
{% extends 'base.html' %}

{% block content %}

    <main>
        <div>
            <h1>Delete Task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Delete</button>
            </form>
        </div>
    </main>

{% endblock content %}

tasks/templates/tasks/mine.html
{% extends 'base.html' %} {% block content %}
<main>
  <div class="my-tasks-list">
    <h2>My Practice Tasks</h2>
    {% if task_list|length == 0 %}
    <p>You have no tasks</p>
    {% else %}
    <table>
      <thead>
        <tr>
          <th>Category</th>
          <th>Task Name</th>
          <th>Goal Time</th>
          <th>Complete?</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for task in task_list %}
        <tr>
          <td>{{ task.project.name }}</td>
          <td>{{ task.name }}</td>
          <td>{{ task.goal_time }}</td>
          <td>
            {% if task.is_completed == False %}
            <form method="post" action="{% url 'complete_task' task.id %}">
              {% csrf_token %}
              <input type="hidden" name="is_completed" value="True" />
              <button>Complete</button>
            </form>
            {% else %} Done {% endif %}
          </td>
          <td>
            <form method="post" action="{% url 'delete_task' task.id %}">
              {% csrf_token %}
              <input type="hidden" name="delete" value="True" />
              <button>&#10006;</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <p style="padding-top: 15px">
      <i
        >Assign more tasks through your
        <a href="/projects/">practice schedule</a></i
      >
    </p>
    {% endif %}
  </div>
  <div style="text-align: center; padding-top: 30px">
    <iframe
      src="https://beepmyclock.com/widget/stopwatch"
      frameborder="0"
      style="border: 0; height: 130px"
    ></iframe
    >>
  </div>
</main>

{% endblock content %}