keys/urls.py
from django.urls import path

from keys.views import KeyListView, KeyCreateView, KeyDeleteView

urlpatterns = [
    path("list/", KeyListView.as_view(), name="list_keys"),
    path("create/", KeyCreateView.as_view(), name="create_key"),
    path("<int:pk>/delete/", KeyDeleteView.as_view(), name="delete_key")
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectDeleteView, 
    metronome,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("metronome/", metronome, name="metronome"),
    path("<int:pk>/delete/", ProjectDeleteView.as_view(), name="delete_project")
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("tasks/", include("tasks.urls")),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("keys/", include("keys.urls")),
    path("admin/", admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

projects/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField("auth.User", related_name="projects")
    goal_time = models.CharField(max_length=100, default="None specified")

    def __str__(self):
        name = self.name
        return name

projects/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from projects.models import Project


# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "goal_time", "members"]
    success_url = reverse_lazy("show_project")

    # very unsure about part below. Wasn't sure how to
    # assign item.members = self.request.user

    def form_valid(self, form):
        item = form.save(commit=False)
        item.auth_User = self.request.user
        item.save()
        form.save_m2m()  # saves many to many relationships
        return redirect("show_project", pk=item.id)


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = "project/delete.html"
    success_url = reverse_lazy("list_projects")


def metronome(request):
    return render(request, "projects/metronome.html")

projects/templates/projects/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class = "project-form">
            <h1>Create a new practice category</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>

{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
    <main>
        <div class = "project-detail">
            <h1>{{ project.name }}</h1>
            <p>{{ project.description|markdownify }}</p>
            <h2>Tasks</h2>
            <p><a href="{%url "create_task" %}">Create a new task</a></p>
            {% if project.tasks.all|length == 0%}
                <p>This project has no tasks</p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Goal Time</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <td>{{ task.name }}</td>
                            <td>{{ task.goal_time }}</td>
                            {% if task.is_completed == True %}
                                <td>yes</td>
                            {% else %}
                                <td>no</td>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block content %}

    <main>
        <div class = "project-list">
            <h1 style="text-align: center">Practice schedule</h1>
            <p style="text-align: center"><a href="{%url "create_project" %}">Create a new category</a></p>
            {% if project_list|length == 0 %}
                <p>You haven't listed any categories</p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Category-<i> click to add tasks</i></th>
                            <th>Description</th>
                            <th>Time Goal</th>
                            <th>Number of tasks</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td> <a href="{%url "show_project" project.pk %}">{{ project.name }}</a></td>
                                <td>{{project.description}}</td>
                                <td>{{project.goal_time}}</td>
                                <td>{{project.tasks.all|length}}</td>
                                <td>
                                    <form method="post" action="{% url 'delete_project' project.id %}">
                                      {% csrf_token %}
                                      <input type="hidden" name="delete" value="True" />
                                      <button>X</button>
                                    </form>
                                  </td>
                                </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>

{% endblock content %}

projects/templates/projects/metronome.html
{% extends 'base.html' %}

{% block content %}


<div class= "project-list">
    <iframe
  src="https://4four.io/embed/metronome"
  width="800" height="400"
  frameborder=".5" text-align = "center">
 <a href="https://4four.io/metronome">
   Metronome
 </a>
</iframe>
</div>

{% endblock content %}